In [19]:
import pickle

import numpy as np
import pandas as pd

In [20]:
data = pickle.load(open("data.pkl", "rb"))
(T_0, O_0) = pickle.load(open("initial-estimates.pkl", "rb"))
(S, A, R, O, T_final, O_final, cid_observation_sequences) = data

In [21]:
# State Space
# Index / row is state id
S

f  c   e
0   A  R  FR
1   A  R  FC
2   A  R  PU
3   A  R  PD
4   A  R  NR
5   A  R  NL
6   A  R  OE
7   A  R   ⊥
8   A  U  FR
9   A  U  FC
10  A  U  PU
11  A  U  PD
12  A  U  NR
13  A  U  NL
14  A  U  OE
15  A  U   ⊥
16  F  R  FR
17  F  R  FC
18  F  R  PU
19  F  R  PD
20  F  R  NR
21  F  R  NL
22  F  R  OE
23  F  R   ⊥
24  F  U  FR
25  F  U  FC
26  F  U  PU
27  F  U  PD
28  F  U  NR
29  F  U  NL
30  F  U  OE
31  F  U   ⊥
32  N  R  FR
33  N  R  FC
34  N  R  PU
35  N  R  PD
36  N  R  NR
37  N  R  NL
38  N  R  OE
39  N  R   ⊥
40  N  U  FR
41  N  U  FC
42  N  U  PU
43  N  U  PD
44  N  U  NR
45  N  U  NL
46  N  U  OE
47  N  U   ⊥

In [22]:
# Action Space
# Index / row is action id
A

0        Do Nothing
1    Alert Operator
Name: action, dtype: object

In [23]:
# Reward Function / Matrix
# R[s, a] gives reward for taking action a in state s
R

array([[  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [  0., -10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,  10.],
       [-20.,

In [24]:
# Observation Space
# Index / row is observation id
O

0             ('Available', 'Reachable')
1               ('Faulted', 'Reachable')
2           ('Unavailable', 'Reachable')
3                   ('Unavailable', '⊥')
4           ('Unreachable', 'Reachable')
5         ('Unreachable', 'Unreachable')
6                                Boot up
7                 Bootup Due to POWER ON
8               Bootup Due to SOFT RESET
9                   Bootup Due to SWITCH
10                Bootup Due to WATCHDOG
11       Circuit Sharing Current Reduced
12      Circuit Sharing Current Restored
13                   Data Partition Full
14        Earth Fault Station In Service
15    Earth Fault Station Out Of Service
16                         Fault Cleared
17                        GFCI Hard Trip
18                  IP Mismatch Detected
19                  Maintenance Required
20                   Manual Intervention
21       Over Current Hard Trip Detected
22                Pilot Unreachable (18)
23          Pilot current level exceeded
24              

In [25]:
# Transition Matrix T
# T[s, s'] gives probability of transitioning from state s to state s'
print(T_final.shape)
T_final

(48, 48)


array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 7.1230998e-33],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 5.7282723e-02],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 2.5704905e-01],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 9.6909052e-01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 3.3032771e-07],
       [2.7241281e-21, 3.4670079e-26, 2.7218506e-23, ..., 4.0111952e-02,
        2.3732428e-02, 4.1357350e-01]], shape=(48, 48), dtype=float32)

In [26]:
# Observation Emission Matrix O
# O[s, o] gives probability of observing o when in state s
print(O_final.shape)
O_final

(48, 31)


array([[8.1691232e-10, 0.0000000e+00, 1.3066439e-02, ..., 0.0000000e+00,
        0.0000000e+00, 8.7012043e-03],
       [1.6040040e-02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [8.7524289e-01, 0.0000000e+00, 1.8465634e-20, ..., 0.0000000e+00,
        0.0000000e+00, 5.2419364e-38],
       ...,
       [2.6701385e-02, 0.0000000e+00, 0.0000000e+00, ..., 7.2938512e-04,
        0.0000000e+00, 9.6222061e-01],
       [9.9998355e-01, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.1582945e-06, 2.0900586e-06],
       [2.3733871e-01, 0.0000000e+00, 0.0000000e+00, ..., 3.2425077e-26,
        0.0000000e+00, 3.6296672e-01]], shape=(48, 31), dtype=float32)

In [ ]:
# Charger Observation Sequences
# cid_observation_sequences[i] gives observation sequence for charger i
print(f"Number of charger observation sequences: {len(cid_observation_sequences)}")

# First 5 charger observation sequences
for i, seq in enumerate(cid_observation_sequences[:5]):
    print(f"Charger {i} observation sequence (length {len(seq)}): {seq}")

In [27]:
def update(b, o, T, O):
    """
    Perform a belief update given prior belief b, observation o,
    transition matrix T, and observation emission matrix O.
    """
    b_prime = np.zeros_like(T_final[0])
    for i, s in enumerate(S.index):
        po = O[s, o]
        sum_term = 0
        for j, s_prev in enumerate(S.index):
            sum_term += T[s_prev, s] * b[j]
        b_prime[i] = po * sum_term

    # Normalize
    b_upd = b_prime / np.sum(b_prime)
        
    return b_upd

In [55]:
b_0 = np.zeros(len(S))
# Uniform over non-event states
num_non_event_states = len(S[S.e == "⊥"])
for s in S[S.e == "⊥"].index:
    b_0[s] = 1 / num_non_event_states
b_0
b = b_0
i = 0

In [58]:
b = update(b, 0, T_final, O_0).round(3)
i += 1
print(f"After observation {i}:")
display(b.round(3))
argmax_state = np.argmax(b)
display(S.iloc[argmax_state].to_frame().T)

After observation 3:


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

f  c  e
7  A  R  ⊥

In [ ]:
O_final[2, 6].round(3)

In [ ]:
np.argmax(O_final[2])